name: tl_consultant
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  audio_session: ^0.1.10
  video_thumbnail: ^0.5.2

  dartz: ^0.10.1
  equatable: ^2.0.5
  get: any #state management, dependency injection and GetMaterial widgets
  connectivity_plus: ^3.0.4
  json_annotation: ^4.6.0
  http_parser: ^4.0.2
  http: any

  get_storage: ^2.1.1
  #flutter_secure_storage: ^6.0.0

  velocity_x: ^3.6.0
  file_picker:
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.1
  path_provider: ^2.0.13
  path_provider_ios: ^2.0.9
  path: ^1.8.3
  language_picker: ^0.4.1

  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  local_auth: ^2.1.2
  permission_handler: ^10.0.0
  photo_view: ^0.14.0
  scrollable_positioned_list: ^0.3.2
  uuid: ^3.0.6
  expandable_page_view: ^1.0.17

  geolocator: ^9.0.2
  geocoding: ^2.1.0

  device_info_plus: ^4.1.2
  dotted_line: ^3.1.0
  draggable_widget: ^2.0.0
  dropdown_button2: ^1.7.2
  fluttermoji: ^1.0.0
  flutter_cache_manager: ^3.3.0
  swipe_to: ^1.0.2
  dotted_border: ^2.0.0+3
  add_2_calendar: ^2.1.3

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.1
  emoji_picker_flutter: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/onboarding/
    - assets/images/chat/
    - assets/images/profile/

  fonts:
    - family: TranquilIcons
      fonts:
        - asset: assets/fonts/TranquilIcons.ttf

    - family: JosefinSansRegular
      fonts:
        - asset: assets/fonts/josefin_sans/JosefinSans-Regular.ttf
    - family: JosefinSansSemiBold
      fonts:
        - asset: assets/fonts/josefin_sans/JosefinSans-SemiBold.ttf
    - family: JosefinSansBold
      fonts:
        - asset: assets/fonts/josefin_sans/JosefinSans-Bold.ttf
    - family: josefinSansLight
      fonts:
        - asset: assets/fonts/josefin_sans/JosefinSans-Light.ttf